server:
    port: 80
spring:
    application:
        name: cloud-consumer-order
    cloud:
        zookeeper:
            connect-string: localserver:2181
        consul:
            host: localhost
            port: 8500
            discovery:
                service-name: ${spring.application.name}
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        password: wajing
        url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC
        username: root