server:
    port: 8002
mybatis:
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package: com.example.cloudApi.entity
spring:
    application:
        name: cloud-payment-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        password: wajing
        url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC
        username: root
eureka:
    instance:
        instance-id: payment8002
        prefer-ip-address: true
    client:
        register-with-eureka: true
        fetchRegistry: true
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka