server:
    port: 8004
mybatis:
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package: com.example.cloudApi.entity
spring:
    application:
        name: cloud-payment-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        password: wajing
        url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC
        username: root
    cloud:
        zookeeper:
            connect-string: localserver:2181